export default [
    {
        level: 1,
        title: "Tile Goal",
        boardWidth: 5,
        boardHeight: 5,
        boardPreset: [
            [1, 2, 1, 1, 2],
            [3, 1, 3, 2, 2],
            [1, 3, 1, 3, 1],
            [4, 4, 2, 1, 2],
            [1, 1, 3, 2, 4],
        ],
        maxMoves: 10,
        goals: [{ tileValue: 5, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        showGoalDialog: "created",
        tutorialSwaps: [
            {
                from: { row: 1, col: 2 },
                to: { row: 2, col: 2 },
                text: "Swap these two tiles to create your first merge",
            },
        ],
    },
    {
        level: 2,
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 30,
        goals: [{ tileValue: 5, target: 2, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 3,
        title: "Blocked Tile Goal",
        maxMoves: 40,
        boardWidth: 6,
        boardHeight: 6,
        boardPreset: [
            [3, 1, 3, 2, 2, 1],
            [4, 2, 1, 2, 3, 1],
            [2, 3, 4, 1, 1, 3],
            [2, 1, 1, 3, 1, 4],
            ["B", "B", "B", "B", "B", "B"],
            ["B", "B", "B", "B", "B", "B"],
        ],
        blockedTiles: [{ row: 4 }, { row: 5 }],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 5, target: 3, current: 0, goalType: "created" },
        ],
        tutorialSwaps: [
            {
                from: { row: 2, col: 3 },
                to: { row: 3, col: 3 },
                text: "Create a merge to clear the blocked tiles nearby",
            },
        ],
        showGoalDialog: "blocked",
    },
    {
        level: 4,
        title: "🔨",
        unlockFeature: "power_up_1",
        maxMoves: 40,
        blockedTiles: [
            { row: 4, col: [1, 2, 3, 4, 5, 6] },
            { row: 5, col: [1, 2, 3, 4, 5, 6] },
            { row: 6, col: [1, 2, 3, 4, 5, 6] },
            { row: 7, col: [1, 2, 3, 4, 5, 6] },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 6, target: 1, current: 0, goalType: "created" },
        ],
    },
    {
        level: 5,
        title: "✂️",
        unlockFeature: "power_up_2",
        maxMoves: 38,
        boardHeight: 10,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 8 }, { row: 9 }],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 5, target: 4, current: 0, goalType: "created" },
            { tileValue: 6, target: 1, current: 0, goalType: "created" },
        ],
    },
    {
        level: 6,
        title: "🔄",
        unlockFeature: "power_up_3",
        boardWidth: 9,
        maxMoves: 36,
        blockedTiles: [
            { row: 4, col: 0 },
            { row: 4, col: 8 },
            { row: 5, col: [0, 1, 7, 8] },
            { row: 6, col: [0, 1, 2, 6, 7, 8] },
            { row: 7, col: [0, 1, 2, 3, 5, 6, 7, 8] },
            { row: 8 },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 6, target: 2, current: 0, goalType: "created" },
        ],
    },
    {
        level: 7,
        maxMoves: 34,
        boardHeight: 9,
        blockedTiles: [{ row: 6 }, { row: 7 }, { row: 8 }, { col: 0 }, { col: 7 }],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 8,
        title: "💸 PoS",
        // freeExtraMoves: true,
        maxMoves: 30,
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 9,
        title: "🔥 Streak",
        unlockFeature: "streak",
        maxMoves: 38,
        blockedTiles: [{ col: 0 }, { col: 1 }, { col: 6 }, { col: 7 }],
        goals: [
            { tileValue: 6, target: 8, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 10,
        title: "Movable Blocked",
        maxMoves: 20,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 3, movable: true },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_movable",
    },
    {
        level: 11,
        maxMoves: 24,
        blockedTiles: [
            { row: 1, col: [1, 2, 3, 4, 5, 6], movable: true },
            { row: 2, col: [1, 6], movable: true },
            { row: 3, col: [1, 6], movable: true },
            { row: 4, col: [1, 6], movable: true },
            { row: 5, col: [1, 6], movable: true },
            { row: 6, col: [1, 2, 3, 4, 5, 6], movable: true },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 6, target: 3, current: 0, goalType: "created" },
        ],
    },
    {
        level: 12,
        maxMoves: 24,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
        ],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
            { current: 0, goalType: "blocked" },
        ],
    },
    {
        level: 13,
        boardHeight: 9,
        maxMoves: 26,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 3, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
        ],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
            { current: 0, goalType: "blocked" },
        ],
        spawnableTiles: [1, 2, 3],
    },

    {
        level: 14,
        title: "Lifebased Blocked",
        maxMoves: 38,
        blockedTiles: [
            { row: 5, lifeValue: 8 },
            { row: 6, lifeValue: 16 },
            { row: 7, lifeValue: 32 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_with_life",
    },
    {
        level: 15,
        boardHeight: 6,
        maxMoves: 30,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, lifeValue: 32 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
    },
    {
        level: 16,
        maxMoves: 32,
        blockedTiles: [
            { row: 3, col: [3, 4], lifeValue: 32 },
            { row: 4, col: [3, 4], lifeValue: 32 },
            { row: 2, col: [2, 3, 4, 5], lifeValue: 16 },
            { row: 3, col: [2, 5], lifeValue: 16 },
            { row: 4, col: [2, 5], lifeValue: 16 },
            { row: 5, col: [2, 3, 4, 5], lifeValue: 16 },
        ],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 17,
        maxMoves: 38,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 6, lifeValue: 8 },
            { row: 7, lifeValue: 32 },
        ],
        goals: [
            { tileValue: 6, target: 10, current: 0, goalType: "created" },
            { current: 0, goalType: "blocked" },
        ],
    },
    {
        level: 18,
        title: "💸 PoS",
        maxMoves: 30,
        boardWidth: 9,
        blockedTiles: [
            { row: 0, col: [4], lifeValue: 64 },
            { row: 1, col: [4], lifeValue: 64 },
            { row: 2, col: [4], lifeValue: 64 },
            { row: 3, col: [4], lifeValue: 64 },
            { row: 4, col: [4], lifeValue: 64 },
            { row: 5, col: [4], lifeValue: 64 },
            { row: 6, col: [4], lifeValue: 64 },
            { row: 7, col: [4], lifeValue: 64 },

            { row: 0, col: [3, 5], movable: true },
            { row: 1, col: [3, 5], movable: true },
            { row: 2, col: [3, 5], movable: true },
            { row: 3, col: [3, 5], movable: true },
            { row: 4, col: [3, 5], movable: true },
            { row: 5, col: [3, 5], movable: true },
            { row: 6, col: [3, 5], movable: true },
            { row: 7, col: [3, 5], movable: true },
        ],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 19,
        title: "Board Upgrades - TODO",
        maxMoves: 32,
        boardWidth: 9,
        blockedTiles: [
            { row: 0, col: [4], lifeValue: 128 },
            { row: 1, col: [4], lifeValue: 128 },
            { row: 2, col: [4], lifeValue: 128 },
            { row: 3, col: [4], lifeValue: 128 },
            { row: 4, col: [4], lifeValue: 128 },
            { row: 5, col: [4], lifeValue: 128 },
            { row: 6, col: [4], lifeValue: 128 },
            { row: 7, col: [4], lifeValue: 128 },

            { row: 0, col: [3, 5], movable: true },
            { row: 1, col: [3, 5], movable: true },
            { row: 2, col: [3, 5], movable: true },
            { row: 3, col: [3, 5], movable: true },
            { row: 4, col: [3, 5], movable: true },
            { row: 5, col: [3, 5], movable: true },
            { row: 6, col: [3, 5], movable: true },
            { row: 7, col: [3, 5], movable: true },
        ],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [5],
        unlockFeature: "board_upgrades",
    },
    {
        level: 20,
        maxMoves: 46,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, lifeValue: 128 },
            { row: 7, lifeValue: 128 },
            { row: 7, col: [2, 3, 4, 5], lifeValue: 256 },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 9, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6, 8],
    },
    {
        level: 21,
        title: "Super Streak",
        maxMoves: 28,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
        ],
        goals: [{ tileValue: 7, target: 10, current: 0, goalType: "created" }],
        boardUpgrades: [6, 8],
        unlockFeature: "super_streak",
    },
    {
        level: 22,
        maxMoves: 20,
        boardHeight: 9,
        blockedTiles: [{ row: 3, movable: true }, { row: 4, movable: true }, { row: 7 }, { row: 8 }],
        goals: [{ tileValue: 9, target: 1, current: 0, goalType: "created" }],
        boardUpgrades: [5, 8],
    },
    {
        level: 23,
        maxMoves: 25,
        boardHeight: 9,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
        ],
        goals: [
            { tileValue: 9, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [5, 6],
    },
    {
        level: 24,
        title: "💸 PoS",
        maxMoves: 32,
        blockedTiles: [
            { row: 4, lifeValue: 8 },
            { row: 5, lifeValue: 16 },
            { row: 6, lifeValue: 32 },
            { row: 7, lifeValue: 64 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6],
    },
    {
        level: 25,
        title: "*Active Super Streak*",
        maxMoves: 32,
        goals: [{ tileValue: 8, target: 5, current: 0, goalType: "created" }],
        boardUpgrades: [7, 8],
    },
    {
        level: 26,
        title: "Blocked Area",
        maxMoves: 22,
        blockedTiles: [
            { row: 2, col: 3, width: 2, height: 2 },
            { row: 4, col: 3, width: 2, height: 2 },
            { row: 6, col: 3, width: 2, height: 2 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_area",
    },
    {
        level: 27,
        maxMoves: 29,
        blockedTiles: [
            { row: 4, col: 0, width: 2, height: 2 },
            { row: 4, col: 2, width: 2, height: 2 },
            { row: 4, col: 4, width: 2, height: 2 },
            { row: 4, col: 6, width: 2, height: 2 },
            { row: 6, col: 0, width: 2, height: 2 },
            { row: 6, col: 2, width: 2, height: 2 },
            { row: 6, col: 4, width: 2, height: 2 },
            { row: 6, col: 6, width: 2, height: 2 },
        ],
        goals: [
            { goalType: "blocked", current: 0 },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6],
    },
    {
        level: 28,
        maxMoves: 25,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, col: 0, width: 2, height: 3 },
            { row: 5, col: 2, width: 2, height: 3 },
            { row: 5, col: 4, width: 2, height: 3 },
            { row: 5, col: 6, width: 2, height: 3 },
        ],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [6],
    },
    {
        level: 29,
        boardWidth: 9,
        maxMoves: 23,
        blockedTiles: [
            { row: 3, col: 0, width: 3, height: 1 },
            { row: 3, col: 3, width: 3, height: 1 },
            { row: 3, col: 6, width: 3, height: 1 },
            { row: 6, col: 0, width: 2, height: 2 },
            { row: 6, col: 2, width: 5, height: 2 },
            { row: 6, col: 7, width: 2, height: 2 },
        ],
        goals: [
            { tileValue: 6, target: 20, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [6, 7],
    },
    {
        level: 30,
        title: "Lifebased Blocked Area",
        maxMoves: 24,
        blockedTiles: [
            { row: 2, col: 3, width: 2, height: 2, lifeValue: 32 },
            { row: 4, col: 3, width: 2, height: 2, lifeValue: 64 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 128 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_area_with_life",
        boardUpgrades: [6],
    },
    {
        level: 31,
        maxMoves: 34,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 2, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 4, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 8],
    },
    {
        level: 32,
        maxMoves: 32,
        blockedTiles: [{ row: 4, col: 2, width: 4, height: 4, lifeValue: 512 }],
        goals: [
            { goalType: "blocked", current: 0 },
            { goalType: "created", tileValue: 8, target: 1, current: 0 },
        ],
        boardUpgrades: [6],
    },
    {
        level: 33,
        maxMoves: 34,
        blockedTiles: [
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 4, col: 2, width: 4, height: 4 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 8],
    },
    {
        level: 34,
        maxMoves: 36,
        blockedTiles: [
            { row: 5, col: 0, width: 8, height: 1 },
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 2, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 4, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [
            { goalType: "blocked", current: 0 },
            { goalType: "created", tileValue: 8, target: 1, current: 0 },
        ],
        boardUpgrades: [7],
    },
    {
        level: 35,
        title: "💸 PoS - God Level",
        maxMoves: 36,
        boardHeight: 10,
        blockedTiles: [
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
            { row: 9, movable: true },
            { row: 4, col: 3, width: 2, height: 2, lifeValue: 1024 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 1024 },
            { row: 8, col: 3, width: 2, height: 2, lifeValue: 1024 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 7, 8],
    },
    {
        level: 36,
        maxMoves: 40,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, lifeValue: 128 },
            { row: 7, lifeValue: 128 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 1024 },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6, 8],
    },
];
