export default [
    {
        level: 1,
        title: "3-Tile Horizontal",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 2,
        title: "3-Tile Vertical",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 3,
        title: "4-Tile Horizontal",
        boardWidth: 6,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 6, 0, 6, 6, 0],
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 4,
        title: "4-Tile Vertical",
        boardWidth: 5,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 5,
        title: "4-Tile Block (2x2)",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 6, 0, 0],
            [0, 0, 6, 0, 6, 0],
            [0, 0, 6, 6, 0, 0],
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 6,
        title: "5-Tile Horizontal",
        boardWidth: 7,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 6, 0, 0, 0],
            [0, 6, 6, 0, 6, 6, 0],
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 7,
        title: "5-Tile Vertical",
        boardWidth: 5,
        boardHeight: 7,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 8,
        title: "L-Formation",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 0, 6, 6, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 9,
        title: "T-Formation",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 6, 0, 0],
            [0, 6, 0, 6, 6],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 10,
        title: "Free Swap Tile Match",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "5S", 6, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 11,
        title: "Sticky Free Swap Tile Match",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "6K", 6, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 12,
        title: "Joker Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, "J", 6, 5, 0],
            [0, 6, 5, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 13,
        title: "Free Swap Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "6S", 7, 7, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 14,
        title: "Sticky Free Swap Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "7K", 7, 7, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 15,
        title: "Life-based Goal Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        blockedTiles: [
            { row: 4, lifeValue: 16 }, // Single blocked tile
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 16,
        title: "Cursed Tiles - Disappear",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 15,
        goals: [
            {
                tileValue: 5, // 32
                target: 2, // Merge 3 cursed 32s successfully
                current: 0,
                goalType: "cursed",
                frequency: 0, // Every 2nd tile of value 32 becomes cursed
                strength: 5, // Player has 5 moves to merge it
                implode: false, // Just disappears
            },
            {
                tileValue: 8, // 32
                target: 1, // Merge 3 cursed 32s successfully
                current: 0,
                goalType: "created",
            },
        ],
        spawnableTiles: [1, 2, 3, 4], // 2, 4, 8, 16
    },
    {
        level: 17,
        title: "Cursed Tiles - Implode",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 20,
        goals: [
            {
                tileValue: 5, // 16
                target: 2, // Merge 2 cursed 16s successfully
                current: 0,
                goalType: "cursed",
                frequency: 1, // Every 3rd tile of value 16 becomes cursed
                strength: 2, // Player has 4 moves to merge it
                implode: true, // Sucks in adjacent tiles when it expires
            },
        ],
        spawnableTiles: [1, 2, 3, 4], // 2, 4, 8
    },
    {
        level: 18,
        title: "Font-Size",
        boardWidth: 5,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 19,
        title: "Next Level State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 2, 2, 2, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 3, target: 1, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0], // 2, 4, 8
    },
    {
        level: 20,
        title: "Loss Level State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 1,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0],
            [0, 0, 0, 0, 0],
            [0, 5, 0, 0, 0],
        ],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0], // 2, 4, 8
    },
    {
        level: 21,
        title: "Pending Swap Test",
        boardWidth: 5,
        boardHeight: 9,
        maxMoves: 10,
        boardPreset: [[], [], [], [], [], [0, 0, 0, 0, 0], [0, 1, 2, 1, 0], [0, 0, 0, 0, 0], [1, 2, 1, 1, 0]],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 22,
        title: "Pending Swap Test 2",
        boardWidth: 5,
        boardHeight: 9,
        maxMoves: 10,
        boardPreset: [[], [], [], [], [], [], [], [, 5, 6, 5, 5], [1, 1, 1, 0, 0]],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 23,
        title: "All Tiles",
        boardWidth: 6,
        boardHeight: 2,
        maxMoves: 10,
        boardPreset: [
            [1, 2, 3, 4, 5, 6],
            [7, 8, 9, 10, 11],
        ],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0],
    },
    {
        level: 24,
        title: "Score Goal",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardUpgrades: [5, 6],
        // boardPreset: [
        //     [0, 0, 0, 0, 0],
        //     [0, 0, 0, 0, 0],
        //     [0, 2, 2, 2, 0],
        //     [0, 0, 0, 0, 0],
        //     [0, 0, 0, 0, 0],
        // ],
        goals: [
            { goalType: "score", target: 10, current: 0 },
            { tileValue: 4, target: 10, current: 0, goalType: "created" },
            { tileValue: 6, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
        showGoalDialog: "score", // First level with score goals
    },
    {
        level: 25,
        title: "Blocked Default Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 26,
        title: "Blocked Immovable Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3, movable: false }, { row: 4, movable: false }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 27,
        title: "Blocked Movable Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3, movable: true }, { row: 4, movable: true }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 28,
        title: "Blocked Area",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 10,
        goals: [{ goalType: "blocked", current: 0 }],
        blockedTiles: [{ row: 3, col: 2, width: 2, height: 3 }],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
    },
    {
        level: 29,
        title: "Blocked Area with Life",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 10,
        goals: [{ goalType: "blocked", current: 0 }],
        blockedTiles: [{ row: 1, col: 2, width: 2, height: 2, lifeValue: 124 }],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
    },
    {
        level: 30,
        title: "Tutorial Swap",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[], [, , 5, ,], [, 5, , 5], [], []],
        goals: [{ tileValue: 5, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3], //[0, 0, 0],
        tutorialSwaps: [
            {
                from: { row: 1, col: 2 },
                to: { row: 2, col: 2 },
                text: "Swap these two tiles to create your first match!",
            },
        ],
    },
    {
        level: 31,
        title: "Tutorial Power-Up - Hammer",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [, 5, 6, 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "hammer",
                    target: { row: 1, col: 2 },
                },
                text: "Use the hammer power-up to remove this tile!",
            },
        ],
    },
    {
        level: 32,
        title: "Tutorial Power-Up - Halve",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [, 5, 7, 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "halve",
                    target: { row: 1, col: 2 },
                },
                text: "Use the halve power-up to reduce this tile's value!",
            },
        ],
    },
    {
        level: 33,
        title: "Tutorial Power-Up - Swap",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [5, , , , 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "swap",
                    target: { row: 1, col: 0 },
                },
                text: "First, activate the swap power-up, then tap this tile...",
            },
            {
                from: { row: 1, col: 0 },
                to: { row: 1, col: 2 },
                text: "...now drag it here to swap with a distant tile",
            },
        ],
    },
    {
        level: 34,
        title: "Test No Moves Left State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 40,
        goals: [{ tileValue: 10, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3, 4, 5, 6, 7],
    },
    {
        level: 35,
        title: "Power Up Rewards",
        boardWidth: 6,
        boardHeight: 7,
        maxMoves: 40,
        spawnableTiles: [1, 2, 3],
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }],
        goals: [
            { tileValue: 6, target: 3, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
    },
    {
        level: 36,
        title: "Solver Hint Test",
        boardPreset: [
            [1, 2, 1, 3, 4, 4, 3, 4],
            [4, 1, 3, 1, 1, 3, 4, 3],
            [3, 5, 4, 2, 4, 2, 4, 1],
            [1, 1, 2, 1, 2, 3, 3, 2],
            [2, 2, 1, 4, 2, 2, 3, 5],
            [3, 1, 2, 4, 3, 1, 2, 1],
            [4, 1, 5, 3, 2, 3, 4, 1],
            [2, 3, 4, 7, 8, 2, 2, "B"],
        ],
        maxMoves: 1,
        goals: [{ current: 0, goalType: "blocked", target: 1 }],
    },
];
