// Constants and configuration for Match 2048 game
export const FEATURE_KEYS = {
    HAMMER: "power_hammer",
    HALVE: "power_halve",
    SWAP: "power_swap",
    STREAK: "streak",
    BOARD_UPGRADES: "board_upgrades",
    SUPER_STREAK: "super_streak",
};

export const TILE_TYPE = {
    NORMAL: "normal",
    BLOCKED: "blocked",
    BLOCKED_WITH_LIFE: "blocked_with_life",
    BLOCKED_MOVABLE: "blocked_movable",
    JOKER: "joker",
    CURSED: "cursed",
};

export const SPECIAL_TILE_TYPES = {
    NONE: "none",
    JOKER: "joker",
    FREESWAP: "freeswap",
    STICKY_FREESWAP: "sticky_freeswap",
    FREESWAP_HORIZONTAL: "freeswap_horizontal",
    FREESWAP_VERTICAL: "freeswap_vertical",
    HAMMER: "hammer",
    HALVER: "halver",
    RANDOM_POWERUP: "random_powerup",
    TELEPORT: "teleport",
    PLUS: "plus",
};

export const FORMATION_TYPES = {
    LINE_4: "line_4",
    BLOCK_4: "block_4",
    LINE_5: "line_5",
    T_FORMATION: "t_formation",
    L_FORMATION: "l_formation",
};

export const DEFAULT_TILE_VALUES = [1, 2, 3, 4]; // Internal representation: 1=2, 2=4, 3=8, 4=16

export const MAX_POWER_UP_USES = 2;

export const SUPER_STREAK_THRESHOLD = 5;

// Test levels for development and testing
export const TEST_LEVELS = [
    {
        level: 1,
        title: "3-Tile Horizontal",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 2,
        title: "3-Tile Vertical",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 3,
        title: "4-Tile Horizontal",
        boardWidth: 6,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 6, 0, 6, 6, 0],
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 4,
        title: "4-Tile Vertical",
        boardWidth: 5,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 5,
        title: "4-Tile Block (2x2)",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 6, 0, 0],
            [0, 0, 6, 0, 6, 0],
            [0, 0, 6, 6, 0, 0],
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 6,
        title: "5-Tile Horizontal",
        boardWidth: 7,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 6, 0, 0, 0],
            [0, 6, 6, 0, 6, 6, 0],
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 7,
        title: "5-Tile Vertical",
        boardWidth: 5,
        boardHeight: 7,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 8,
        title: "L-Formation",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 0, 6, 6, 0],
            [0, 0, 6, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 9,
        title: "T-Formation",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 6, 0, 0],
            [0, 6, 0, 6, 6],
            [0, 0, 6, 0, 0],
            [0, 0, 6, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 10,
        title: "Free Swap Tile Match",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "5S", 6, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 11,
        title: "Sticky Free Swap Tile Match",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "6K", 6, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 12,
        title: "Joker Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, "J", 6, 5, 0],
            [0, 6, 5, 6, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [
            { tileValue: 1, target: 1, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        spawnableTiles: [0],
    },
    {
        level: 13,
        title: "Free Swap Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "6S", 7, 7, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 14,
        title: "Sticky Free Swap Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 5,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, "7K", 7, 7, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 15,
        title: "Life-based Goal Tile",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        blockedTiles: [
            { row: 4, lifeValue: 16 }, // Single blocked tile
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 16,
        title: "Cursed Tiles - Disappear",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 15,
        goals: [
            {
                tileValue: 5, // 32
                target: 2, // Merge 3 cursed 32s successfully
                current: 0,
                goalType: "cursed",
                frequency: 0, // Every 2nd tile of value 32 becomes cursed
                strength: 5, // Player has 5 moves to merge it
                implode: false, // Just disappears
            },
            {
                tileValue: 8, // 32
                target: 1, // Merge 3 cursed 32s successfully
                current: 0,
                goalType: "created",
            },
        ],
        spawnableTiles: [1, 2, 3, 4], // 2, 4, 8, 16
    },
    {
        level: 17,
        title: "Cursed Tiles - Implode",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 20,
        goals: [
            {
                tileValue: 5, // 16
                target: 2, // Merge 2 cursed 16s successfully
                current: 0,
                goalType: "cursed",
                frequency: 1, // Every 3rd tile of value 16 becomes cursed
                strength: 2, // Player has 4 moves to merge it
                implode: true, // Sucks in adjacent tiles when it expires
            },
        ],
        spawnableTiles: [1, 2, 3, 4], // 2, 4, 8
    },
    {
        level: 18,
        title: "Font-Size",
        boardWidth: 5,
        boardHeight: 6,
        maxMoves: 5,
        boardPreset: [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
        ],
        goals: [{ tileValue: 1, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [0],
    },
    {
        level: 19,
        title: "Next Level State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 2, 2, 2, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ],
        goals: [{ tileValue: 3, target: 1, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0], // 2, 4, 8
    },
    {
        level: 20,
        title: "Loss Level State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 1,
        boardPreset: [
            [0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0],
            [0, 0, 0, 0, 0],
            [0, 5, 0, 0, 0],
        ],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0], // 2, 4, 8
    },
    {
        level: 21,
        title: "Pending Swap Test",
        boardWidth: 5,
        boardHeight: 9,
        maxMoves: 10,
        boardPreset: [[], [], [], [], [], [0, 0, 0, 0, 0], [0, 1, 2, 1, 0], [0, 0, 0, 0, 0], [1, 2, 1, 1, 0]],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 22,
        title: "Pending Swap Test 2",
        boardWidth: 5,
        boardHeight: 9,
        maxMoves: 10,
        boardPreset: [[], [], [], [], [], [], [], [, 5, 6, 5, 5], [1, 1, 1, 0, 0]],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [1, 2, 3],
    },
    {
        level: 23,
        title: "All Tiles",
        boardWidth: 6,
        boardHeight: 2,
        maxMoves: 10,
        boardPreset: [
            [1, 2, 3, 4, 5, 6],
            [7, 8, 9, 10, 11],
        ],
        goals: [{ tileValue: 4, target: 10, current: 0, goalType: "created" }], // 32
        spawnableTiles: [0],
    },
    {
        level: 24,
        title: "Score Goal",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardUpgrades: [5, 6],
        // boardPreset: [
        //     [0, 0, 0, 0, 0],
        //     [0, 0, 0, 0, 0],
        //     [0, 2, 2, 2, 0],
        //     [0, 0, 0, 0, 0],
        //     [0, 0, 0, 0, 0],
        // ],
        goals: [
            { goalType: "score", target: 10, current: 0 },
            { tileValue: 4, target: 10, current: 0, goalType: "created" },
            { tileValue: 6, target: 2, current: 0, goalType: "created" },
        ],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
        showGoalDialog: "score", // First level with score goals
    },
    {
        level: 25,
        title: "Blocked Default Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 26,
        title: "Blocked Immovable Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3, movable: false }, { row: 4, movable: false }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 27,
        title: "Blocked Movable Tiles",
        maxMoves: 10,
        boardHeight: 10,
        blockedTiles: [{ row: 3, movable: true }, { row: 4, movable: true }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3, 4],
    },
    {
        level: 28,
        title: "Blocked Area",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 10,
        goals: [{ goalType: "blocked", current: 0 }],
        blockedTiles: [{ row: 3, col: 2, width: 2, height: 3 }],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
    },
    {
        level: 29,
        title: "Blocked Area with Life",
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 10,
        goals: [{ goalType: "blocked", current: 0 }],
        blockedTiles: [{ row: 1, col: 2, width: 2, height: 2, lifeValue: 124 }],
        spawnableTiles: [1, 2, 3, 4], //[0, 0, 0],
    },
    {
        level: 30,
        title: "Tutorial Swap",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[], [, , 5, ,], [, 5, , 5], [], []],
        goals: [{ tileValue: 5, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3], //[0, 0, 0],
        tutorialSwaps: [
            {
                from: { row: 1, col: 2 },
                to: { row: 2, col: 2 },
                text: "Swap these two tiles to create your first match!",
            },
        ],
    },
    {
        level: 31,
        title: "Tutorial Power-Up - Hammer",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [, 5, 6, 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "hammer",
                    target: { row: 1, col: 2 },
                },
                text: "Use the hammer power-up to remove this tile!",
            },
        ],
    },
    {
        level: 32,
        title: "Tutorial Power-Up - Halve",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [, 5, 7, 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "halve",
                    target: { row: 1, col: 2 },
                },
                text: "Use the halve power-up to reduce this tile's value!",
            },
        ],
    },
    {
        level: 33,
        title: "Tutorial Power-Up - Swap",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 10,
        boardPreset: [[, , 5, ,], [5, , , , 5], [, , 5, ,], [], []],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3],
        tutorialSwaps: [
            {
                powerUp: {
                    type: "swap",
                    target: { row: 1, col: 0 },
                },
                text: "First, activate the swap power-up, then tap this tile...",
            },
            {
                from: { row: 1, col: 0 },
                to: { row: 1, col: 2 },
                text: "...now drag it here to swap with a distant tile",
            },
        ],
    },
    {
        level: 34,
        title: "Test No Moves Left State",
        boardWidth: 5,
        boardHeight: 5,
        maxMoves: 40,
        goals: [{ tileValue: 10, target: 1, current: 0, goalType: "created" }],
        spawnableTiles: [1, 2, 3, 4, 5, 6, 7],
    },
    {
        level: 11,
        title: "Power Up Rewards",
        boardWidth: 6,
        boardHeight: 7,
        maxMoves: 40,
        spawnableTiles: [1, 2, 3],
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }],
        goals: [
            { tileValue: 6, target: 3, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
        powerUpRewards: [5, 6, 7, 8], // Grant power-up when 32 or 64 is created
    },
];

export const NEW_LEVELS = [
    {
        level: 1,
        title: "Blocked Tile Goal",
        boardWidth: 5,
        boardHeight: 5,
        boardPreset: [
            [1, 2, 1, 1, 3],
            [3, 1, 2, 3, 2],
            [1, 2, 1, 2, 3],
            [, "B", "B", "B"],
            [, "B", "B", "B"],
        ],
        maxMoves: 10,
        goals: [{ current: 0, goalType: "blocked" }],
        blockedTiles: [
            { row: 3, col: [1, 2, 3] },
            { row: 4, col: [1, 2, 3] },
        ],
        spawnableTiles: [1, 2, 3],
        showGoalDialog: "blocked",
        tutorialSwaps: [
            {
                from: { row: 1, col: 2 },
                to: { row: 2, col: 2 },
                text: "Create a merge to clear the blocked tiles",
            },
        ],
    },
    {
        level: 2,
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 30,
        blockedTiles: [{ row: 4 }, { row: 5 }],
        goals: [{ current: 0, goalType: "blocked" }],
        spawnableTiles: [1, 2, 3],
        showGoalDialog: "blocked",
    },
    {
        level: 3,
        maxMoves: 40,
        blockedTiles: [
            { row: 4, col: [1, 2, 3, 4, 5, 6] },
            { row: 5, col: [1, 2, 3, 4, 5, 6] },
            { row: 6, col: [1, 2, 3, 4, 5, 6] },
            { row: 7, col: [1, 2, 3, 4, 5, 6] },
        ],
        goals: [{ current: 0, goalType: "blocked" }],
    },
    {
        level: 4,
        title: "🔨",
        maxMoves: 30,
        boardHeight: 10,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        unlockFeature: "power_hammer",
    },
    {
        level: 5,
        boardWidth: 9,
        maxMoves: 32,
        blockedTiles: [
            { row: 4, col: 0 },
            { row: 4, col: 8 },
            { row: 5, col: [0, 1, 7, 8] },
            { row: 6, col: [0, 1, 2, 6, 7, 8] },
            { row: 7, col: [0, 1, 2, 3, 5, 6, 7, 8] },
            { row: 8 },
        ],
        goals: [{ current: 0, goalType: "blocked" }],
    },
    {
        level: 6,
        title: "✂️",
        maxMoves: 25,
        blockedTiles: [{ col: 0 }, { col: 1 }, { col: 6 }, { col: 7 }],
        goals: [{ current: 0, goalType: "blocked" }],
        unlockFeature: "power_halve",
    },
    {
        level: 7,
        maxMoves: 28,
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [{ current: 0, goalType: "blocked" }],
    },
    {
        level: 8,
        title: "🔄",
        maxMoves: 28,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 8 }, { row: 9 }],
        goals: [{ current: 0, goalType: "blocked" }],
        unlockFeature: "power_swap",
    },
    {
        level: 9,
        maxMoves: 32,
        blockedTiles: [{ row: 3 }, { row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [{ current: 0, goalType: "blocked" }],
    },
    {
        title: "Tile Goal",
        level: 10,
        boardWidth: 6,
        boardHeight: 6,
        maxMoves: 35,
        spawnableTiles: [1, 2, 3],
        goals: [{ tileValue: 6, target: 1, current: 0, goalType: "created" }],
        blockedTiles: [{ row: 4 }, { row: 5 }],
        showGoalDialog: "created",
    },
    {
        level: 11,
        boardWidth: 6,
        boardHeight: 7,
        maxMoves: 40,
        spawnableTiles: [1, 2, 3],
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }],
        goals: [
            { tileValue: 6, target: 3, current: 0, goalType: "created" },
            { tileValue: 7, target: 1, current: 0, goalType: "created" },
        ],
    },
    {
        level: 12,
        maxMoves: 15,
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [{ tileValue: 6, target: 10, current: 0, goalType: "created" }],
    },
    {
        level: 13,
        title: "🔥 Streak",
        maxMoves: 22,
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
        unlockFeature: "streak",
    },
    {
        level: 14,
        maxMoves: 30,
        boardWidth: 6,
        boardHeight: 10,
        blockedTiles: [{ row: 5 }, { row: 6 }, { row: 7 }, { row: 8 }, { row: 9 }],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 15,
        maxMoves: 30,
        boardHeight: 9,
        blockedTiles: [{ row: 6 }, { row: 7 }, { row: 8 }, { col: 0 }, { col: 7 }],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 16,
        title: "💸 PoS",
        maxMoves: 30,
        blockedTiles: [{ row: 4 }, { row: 5 }, { row: 6 }, { row: 7 }],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 17,
        title: "Movable Blocked",
        maxMoves: 16,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 3, movable: true },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_movable",
    },
    {
        level: 18,
        maxMoves: 20,
        blockedTiles: [
            { row: 1, col: [1, 2, 3, 4, 5, 6], movable: true },
            { row: 2, col: [1, 6], movable: true },
            { row: 3, col: [1, 6], movable: true },
            { row: 4, col: [1, 6], movable: true },
            { row: 5, col: [1, 6], movable: true },
            { row: 6, col: [1, 2, 3, 4, 5, 6], movable: true },
        ],
        goals: [{ current: 0, goalType: "blocked" }],
    },
    {
        level: 19,
        maxMoves: 22,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
        ],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "current" },
            { current: 0, goalType: "blocked" },
        ],
    },
    {
        level: 20,
        boardHeight: 9,
        maxMoves: 24,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 3, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
        ],
        goals: [
            { tileValue: 7, target: 1, current: 0, goalType: "current" },
            { current: 0, goalType: "blocked" },
        ],
        spawnableTiles: [1, 2, 3],
    },

    {
        level: 21,
        title: "Lifebased Blocked",
        maxMoves: 38,
        blockedTiles: [
            { row: 5, lifeValue: 8 },
            { row: 6, lifeValue: 16 },
            { row: 7, lifeValue: 32 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_with_life",
    },
    {
        level: 22,
        boardHeight: 6,
        maxMoves: 30,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, lifeValue: 32 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
    },
    {
        level: 23,
        maxMoves: 32,
        blockedTiles: [
            { row: 3, col: [3, 4], lifeValue: 32 },
            { row: 4, col: [3, 4], lifeValue: 32 },
            { row: 2, col: [2, 3, 4, 5], lifeValue: 16 },
            { row: 3, col: [2, 5], lifeValue: 16 },
            { row: 4, col: [2, 5], lifeValue: 16 },
            { row: 5, col: [2, 3, 4, 5], lifeValue: 16 },
        ],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 24,
        maxMoves: 38,
        blockedTiles: [
            { row: 0, movable: true },
            { row: 1, movable: true },
            { row: 2, movable: true },
            { row: 6, lifeValue: 8 },
            { row: 7, lifeValue: 32 },
        ],
        goals: [
            { tileValue: 6, target: 10, current: 0, goalType: "created" },
            { current: 0, goalType: "blocked" },
        ],
    },
    {
        level: 25,
        title: "💸 PoS",
        maxMoves: 30,
        boardWidth: 9,
        blockedTiles: [
            { row: 0, col: [4], lifeValue: 64 },
            { row: 1, col: [4], lifeValue: 64 },
            { row: 2, col: [4], lifeValue: 64 },
            { row: 3, col: [4], lifeValue: 64 },
            { row: 4, col: [4], lifeValue: 64 },
            { row: 5, col: [4], lifeValue: 64 },
            { row: 6, col: [4], lifeValue: 64 },
            { row: 7, col: [4], lifeValue: 64 },

            { row: 0, col: [3, 5], movable: true },
            { row: 1, col: [3, 5], movable: true },
            { row: 2, col: [3, 5], movable: true },
            { row: 3, col: [3, 5], movable: true },
            { row: 4, col: [3, 5], movable: true },
            { row: 5, col: [3, 5], movable: true },
            { row: 6, col: [3, 5], movable: true },
            { row: 7, col: [3, 5], movable: true },
        ],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
    },
    {
        level: 26,
        title: "Board Upgrades",
        maxMoves: 32,
        boardWidth: 9,
        blockedTiles: [
            { row: 0, col: [4], lifeValue: 128 },
            { row: 1, col: [4], lifeValue: 128 },
            { row: 2, col: [4], lifeValue: 128 },
            { row: 3, col: [4], lifeValue: 128 },
            { row: 4, col: [4], lifeValue: 128 },
            { row: 5, col: [4], lifeValue: 128 },
            { row: 6, col: [4], lifeValue: 128 },
            { row: 7, col: [4], lifeValue: 128 },

            { row: 0, col: [3, 5], movable: true },
            { row: 1, col: [3, 5], movable: true },
            { row: 2, col: [3, 5], movable: true },
            { row: 3, col: [3, 5], movable: true },
            { row: 4, col: [3, 5], movable: true },
            { row: 5, col: [3, 5], movable: true },
            { row: 6, col: [3, 5], movable: true },
            { row: 7, col: [3, 5], movable: true },
        ],
        goals: [
            { tileValue: 8, target: 1, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [5],
        unlockFeature: "board_upgrades",
    },
    {
        level: 27,
        maxMoves: 46,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, lifeValue: 128 },
            { row: 7, lifeValue: 128 },
            { row: 7, col: [2, 3, 4, 5], lifeValue: 256 },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 9, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6, 8],
    },
    {
        level: 28,
        title: "Super Streak",
        maxMoves: 28,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
        ],
        goals: [{ tileValue: 7, target: 10, current: 0, goalType: "created" }],
        boardUpgrades: [6, 8],
        unlockFeature: "super_streak",
    },
    {
        level: 29,
        maxMoves: 20,
        boardHeight: 9,
        blockedTiles: [{ row: 3, movable: true }, { row: 4, movable: true }, { row: 7 }, { row: 8 }],
        goals: [{ tileValue: 9, target: 1, current: 0, goalType: "current" }],
        boardUpgrades: [5, 8],
    },
    {
        level: 30,
        maxMoves: 25,
        boardHeight: 9,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
        ],
        goals: [
            { tileValue: 9, target: 1, current: 0, goalType: "created" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [5, 6],
    },
    {
        level: 31,
        maxMoves: 32,
        blockedTiles: [
            { row: 4, lifeValue: 8 },
            { row: 5, lifeValue: 16 },
            { row: 6, lifeValue: 32 },
            { row: 7, lifeValue: 64 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6],
    },
    {
        level: 32,
        title: "*Active Super Streak*",
        maxMoves: 32,
        goals: [{ tileValue: 8, target: 5, current: 0, goalType: "current" }],
        boardUpgrades: [7, 8],
    },
    {
        level: 33,
        title: "Blocked Area",
        maxMoves: 22,
        blockedTiles: [
            { row: 2, col: 3, width: 2, height: 2 },
            { row: 4, col: 3, width: 2, height: 2 },
            { row: 6, col: 3, width: 2, height: 2 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_area",
    },
    {
        level: 34,
        maxMoves: 29,
        blockedTiles: [
            { row: 4, col: 0, width: 2, height: 2 },
            { row: 4, col: 2, width: 2, height: 2 },
            { row: 4, col: 4, width: 2, height: 2 },
            { row: 4, col: 6, width: 2, height: 2 },
            { row: 6, col: 0, width: 2, height: 2 },
            { row: 6, col: 2, width: 2, height: 2 },
            { row: 6, col: 4, width: 2, height: 2 },
            { row: 6, col: 6, width: 2, height: 2 },
        ],
        goals: [
            { goalType: "blocked", current: 0 },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6],
    },
    {
        level: 35,
        maxMoves: 25,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, col: 0, width: 2, height: 3 },
            { row: 5, col: 2, width: 2, height: 3 },
            { row: 5, col: 4, width: 2, height: 3 },
            { row: 5, col: 6, width: 2, height: 3 },
        ],
        goals: [
            { tileValue: 7, target: 2, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [6],
    },
    {
        level: 36,
        boardWidth: 9,
        maxMoves: 23,
        blockedTiles: [
            { row: 3, col: 0, width: 3, height: 1 },
            { row: 3, col: 3, width: 3, height: 1 },
            { row: 3, col: 6, width: 3, height: 1 },
            { row: 6, col: 0, width: 2, height: 2 },
            { row: 6, col: 2, width: 5, height: 2 },
            { row: 6, col: 7, width: 2, height: 2 },
        ],
        goals: [
            { tileValue: 6, target: 20, current: 0, goalType: "current" },
            { goalType: "blocked", current: 0 },
        ],
        boardUpgrades: [6, 7],
    },
    {
        level: 37,
        title: "Lifebased Blocked Area",
        maxMoves: 24,
        blockedTiles: [
            { row: 2, col: 3, width: 2, height: 2, lifeValue: 32 },
            { row: 4, col: 3, width: 2, height: 2, lifeValue: 64 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 128 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        showGoalDialog: "blocked_area_with_life",
        boardUpgrades: [6],
    },
    {
        level: 38,
        maxMoves: 34,
        blockedTiles: [
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 2, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 4, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 8],
    },
    {
        level: 39,
        maxMoves: 32,
        blockedTiles: [{ row: 4, col: 2, width: 4, height: 4, lifeValue: 512 }],
        goals: [
            { goalType: "blocked", current: 0 },
            { goalType: "created", tileValue: 8, target: 1, current: 0 },
        ],
        boardUpgrades: [6],
    },
    {
        level: 40,
        maxMoves: 34,
        blockedTiles: [
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 4, col: 2, width: 4, height: 4 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 8],
    },
    {
        level: 41,
        maxMoves: 36,
        blockedTiles: [
            { row: 5, col: 0, width: 8, height: 1 },
            { row: 6, col: 0, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 2, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 4, width: 2, height: 2, lifeValue: 256 },
            { row: 6, col: 6, width: 2, height: 2, lifeValue: 256 },
        ],
        goals: [
            { goalType: "blocked", current: 0 },
            { goalType: "created", tileValue: 8, target: 1, current: 0 },
        ],
        boardUpgrades: [7],
    },
    {
        level: 42,
        title: "💸 PoS - God Level",
        maxMoves: 36,
        boardHeight: 10,
        blockedTiles: [
            { row: 5, movable: true },
            { row: 6, movable: true },
            { row: 7, movable: true },
            { row: 8, movable: true },
            { row: 9, movable: true },
            { row: 4, col: 3, width: 2, height: 2, lifeValue: 1024 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 1024 },
            { row: 8, col: 3, width: 2, height: 2, lifeValue: 1024 },
        ],
        goals: [{ goalType: "blocked", current: 0 }],
        boardUpgrades: [6, 7, 8],
    },
    {
        level: 43,
        title: "Joker Rewards",
        maxMoves: 40,
        blockedTiles: [
            { row: 3, movable: true },
            { row: 4, movable: true },
            { row: 5, movable: true },
            { row: 6, lifeValue: 128 },
            { row: 7, lifeValue: 128 },
            { row: 6, col: 3, width: 2, height: 2, lifeValue: 1024 },
        ],
        goals: [
            { current: 0, goalType: "blocked" },
            { tileValue: 8, target: 1, current: 0, goalType: "created" },
        ],
        boardUpgrades: [6, 8],
        powerUpRewards: [5, 6, 7],
    },
];

// Level configuration options
export const LEVEL_CONFIGS = [
    {
        key: "new",
        name: "Default",
        levels: NEW_LEVELS,
        respectsFeatureLocks: true,
    },
    {
        key: "test",
        name: "Test Levels",
        levels: TEST_LEVELS,
        respectsFeatureLocks: false,
    },
];

export const DEFAULT_LEVEL = NEW_LEVELS;
